---
# https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933
- name: Remove Docker GPG key from trusted.gpg
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: absent
    keyring: /etc/apt/trusted.gpg
  tags: packages

- name: Add Docker GPG key as recommended
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
  tags: packages

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  tags: packages

- name: Install docker required packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
      - lsb-release
  tags: packages

- name: Install Docker Community Edition
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: packages

- name: Remove Docker Compose Package
  apt:
    name: docker-compose
    state: absent
  tags: packages

# install docker-compose from another role
- import_tasks: compose.yml
  tags: packages

- name: Add docker configuration file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker
  tags: configure

- name: ensure docker started
  service: name=docker state=started enabled=yes
  tags: service
